// Generated by LiveScript 1.4.0
(function(){
  var SceneDriver, writeMe, Game, game, Log, log, sceneDriver, baseScenes;
  SceneDriver = require('./scene-driver').SceneDriver;
  writeMe = function(){
    throw {
      name: "Not Implemented",
      message: "Write me!"
    };
  };
  Game = (function(){
    Game.displayName = 'Game';
    var prototype = Game.prototype, constructor = Game;
    function Game(){
      var this$ = this instanceof ctor$ ? this : new ctor$;
      this$.justStarted = true;
      return this$;
    } function ctor$(){} ctor$.prototype = prototype;
    return Game;
  }());
  game = new Game();
  Log = require('./log').Log;
  log = new Log(document.querySelector('#log'));
  sceneDriver = new SceneDriver(log);
  baseScenes = require('./scenes').scenes;
  sceneDriver.addScenes(baseScenes);
  sceneDriver.playScene(game);
}).call(this);
