// Generated by LiveScript 1.4.0
(function(){
  var ss, scenes, out$ = typeof exports != 'undefined' && exports || this;
  ss = 'schopen';
  out$.scenes = scenes = [
    {
      title: "The First Scene",
      condition: function(it){
        return !!it.justStarted;
      },
      script: function(it){
        this.say(ss, "Welcome to the demo for Boundless. Tap to continue.");
        return it.justStarted = false;
      }
    }, {
      title: "Moving on",
      condition: function(it){
        return !it.justStarted;
      },
      script: function(game){
        var this$ = this;
        this.say(ss, "You may not have noticed, but we just entered the second scene.");
        this.say(ss, "Let's demonstrate a choice. What is your favorite color?");
        this.choose('red', "Red", function(){
          this$.say(ss, "A fine color.");
          return game.color = 'red';
        });
        this.choose('blue', "Blue", function(){
          this$.say(ss, "Seriously?");
          return game.color = 'blue';
        });
        return this.choose('bunny', "Bunny", function(){
          this$.say(ss, "That's not even a color! What are you doing?");
          return game.color = 'bunny';
        });
      }
    }
  ];
}).call(this);
