// Generated by LiveScript 1.4.0
(function(){
  var random, R, pick, capitalize, remove, contains, shuffle, middle, scrollBottom, out$ = typeof exports != 'undefined' && exports || this;
  random = require('seedrandom')('test');
  out$.R = R = function(it){
    return ~~(it * random());
  };
  out$.pick = pick = function(it){
    return it[R(it.length)];
  };
  out$.capitalize = capitalize = function(it){
    return it[0].toUpperCase() + it.substr(1);
  };
  out$.remove = remove = function(arr, item){
    var arr2;
    arr2 = arr.slice(0);
    arr2.splice(arr2.indexOf(item), 1);
    return arr2;
  };
  out$.contains = contains = function(arr, item){
    return -1 < arr.indexOf(item);
  };
  out$.shuffle = shuffle = function(it){
    var arr, i$, to$, ii, jj, tmp;
    arr = it.slice(0);
    for (i$ = 0, to$ = arr.length - 2; i$ <= to$; ++i$) {
      ii = i$;
      jj = ii + R(arr.length - ii);
      tmp = arr[ii];
      arr[ii] = arr[jj];
      arr[jj] = tmp;
    }
    return arr;
  };
  out$.middle = middle = function(a, b, c){
    if (a >= b) {
      if (b >= c) {
        return b;
      }
      if (a >= c) {
        return c;
      }
      return a;
    }
    if (a >= c) {
      return a;
    }
    if (b >= c) {
      return c;
    }
    return b;
  };
  out$.scrollBottom = scrollBottom = function(){
    return window.scrollTo(0, 1000000);
  };
}).call(this);
